# Generated by Django 3.2.4 on 2021-06-09 18:19

import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cast",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ],
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("genre", models.CharField(max_length=45, unique=True, verbose_name="название")),
            ],
            options={
                "verbose_name": "жанр",
                "verbose_name_plural": "жанры",
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("first_name", models.CharField(max_length=45)),
                ("last_name", models.CharField(max_length=45)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                "verbose_name": "актеры, режиссеры и сценаристы",
                "verbose_name_plural": "состав",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("actor", "актёр"), ("director", "режиссёр"), ("writer", "сценарист")],
                        max_length=45,
                        unique=True,
                        verbose_name="тип",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FilmWork",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="название")),
                ("description", models.TextField(blank=True, verbose_name="описание")),
                ("creation_date", models.DateField(blank=True, verbose_name="дата создания фильма")),
                ("certificate", models.TextField(blank=True, verbose_name="сертификат")),
                ("file_path", models.FileField(blank=True, null=True, upload_to="film_works/", verbose_name="файл")),
                (
                    "rating",
                    models.FloatField(
                        blank=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name="рейтинг"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("movie", "фильм"), ("tv_show", "шоу")], max_length=20, verbose_name="тип"
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("genres", models.ManyToManyField(related_name="film_works", to="movies.Genre")),
                (
                    "people",
                    models.ManyToManyField(related_name="film_works", through="movies.Cast", to="movies.Person"),
                ),
            ],
            options={
                "verbose_name": "кинопроизведение",
                "verbose_name_plural": "кинопроизведения",
            },
        ),
        migrations.AddField(
            model_name="cast",
            name="film_work",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="movies.filmwork"),
        ),
        migrations.AddField(
            model_name="cast",
            name="person",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="movies.person"),
        ),
        migrations.AddField(
            model_name="cast",
            name="role",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="movies.role"),
        ),
    ]
