version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - ./.env_prod
    restart: always
    ports:
      - "5432:5432"
  web:
    build: .
    volumes:
      - static_volume:/static_files
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env_prod
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - static_volume:/static_files
volumes:
  pg_data:
  static_volume:
